// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"cowpoke/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRancherClient creates a new instance of MockRancherClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRancherClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRancherClient {
	mock := &MockRancherClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRancherClient is an autogenerated mock type for the RancherClient type
type MockRancherClient struct {
	mock.Mock
}

type MockRancherClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRancherClient) EXPECT() *MockRancherClient_Expecter {
	return &MockRancherClient_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type MockRancherClient
func (_mock *MockRancherClient) Authenticate(ctx context.Context, server domain.ConfigServer, password string) (domain.AuthToken, error) {
	ret := _mock.Called(ctx, server, password)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 domain.AuthToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ConfigServer, string) (domain.AuthToken, error)); ok {
		return returnFunc(ctx, server, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ConfigServer, string) domain.AuthToken); ok {
		r0 = returnFunc(ctx, server, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.AuthToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ConfigServer, string) error); ok {
		r1 = returnFunc(ctx, server, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRancherClient_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockRancherClient_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - server domain.ConfigServer
//   - password string
func (_e *MockRancherClient_Expecter) Authenticate(ctx interface{}, server interface{}, password interface{}) *MockRancherClient_Authenticate_Call {
	return &MockRancherClient_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, server, password)}
}

func (_c *MockRancherClient_Authenticate_Call) Run(run func(ctx context.Context, server domain.ConfigServer, password string)) *MockRancherClient_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ConfigServer
		if args[1] != nil {
			arg1 = args[1].(domain.ConfigServer)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRancherClient_Authenticate_Call) Return(authToken domain.AuthToken, err error) *MockRancherClient_Authenticate_Call {
	_c.Call.Return(authToken, err)
	return _c
}

func (_c *MockRancherClient_Authenticate_Call) RunAndReturn(run func(ctx context.Context, server domain.ConfigServer, password string) (domain.AuthToken, error)) *MockRancherClient_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// GetKubeconfig provides a mock function for the type MockRancherClient
func (_mock *MockRancherClient) GetKubeconfig(ctx context.Context, token domain.AuthToken, server domain.ConfigServer, clusterID string) ([]byte, error) {
	ret := _mock.Called(ctx, token, server, clusterID)

	if len(ret) == 0 {
		panic("no return value specified for GetKubeconfig")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AuthToken, domain.ConfigServer, string) ([]byte, error)); ok {
		return returnFunc(ctx, token, server, clusterID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AuthToken, domain.ConfigServer, string) []byte); ok {
		r0 = returnFunc(ctx, token, server, clusterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.AuthToken, domain.ConfigServer, string) error); ok {
		r1 = returnFunc(ctx, token, server, clusterID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRancherClient_GetKubeconfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKubeconfig'
type MockRancherClient_GetKubeconfig_Call struct {
	*mock.Call
}

// GetKubeconfig is a helper method to define mock.On call
//   - ctx context.Context
//   - token domain.AuthToken
//   - server domain.ConfigServer
//   - clusterID string
func (_e *MockRancherClient_Expecter) GetKubeconfig(ctx interface{}, token interface{}, server interface{}, clusterID interface{}) *MockRancherClient_GetKubeconfig_Call {
	return &MockRancherClient_GetKubeconfig_Call{Call: _e.mock.On("GetKubeconfig", ctx, token, server, clusterID)}
}

func (_c *MockRancherClient_GetKubeconfig_Call) Run(run func(ctx context.Context, token domain.AuthToken, server domain.ConfigServer, clusterID string)) *MockRancherClient_GetKubeconfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.AuthToken
		if args[1] != nil {
			arg1 = args[1].(domain.AuthToken)
		}
		var arg2 domain.ConfigServer
		if args[2] != nil {
			arg2 = args[2].(domain.ConfigServer)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRancherClient_GetKubeconfig_Call) Return(bytes []byte, err error) *MockRancherClient_GetKubeconfig_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockRancherClient_GetKubeconfig_Call) RunAndReturn(run func(ctx context.Context, token domain.AuthToken, server domain.ConfigServer, clusterID string) ([]byte, error)) *MockRancherClient_GetKubeconfig_Call {
	_c.Call.Return(run)
	return _c
}

// ListClusters provides a mock function for the type MockRancherClient
func (_mock *MockRancherClient) ListClusters(ctx context.Context, token domain.AuthToken, server domain.ConfigServer) ([]domain.Cluster, error) {
	ret := _mock.Called(ctx, token, server)

	if len(ret) == 0 {
		panic("no return value specified for ListClusters")
	}

	var r0 []domain.Cluster
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AuthToken, domain.ConfigServer) ([]domain.Cluster, error)); ok {
		return returnFunc(ctx, token, server)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AuthToken, domain.ConfigServer) []domain.Cluster); ok {
		r0 = returnFunc(ctx, token, server)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Cluster)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.AuthToken, domain.ConfigServer) error); ok {
		r1 = returnFunc(ctx, token, server)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRancherClient_ListClusters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClusters'
type MockRancherClient_ListClusters_Call struct {
	*mock.Call
}

// ListClusters is a helper method to define mock.On call
//   - ctx context.Context
//   - token domain.AuthToken
//   - server domain.ConfigServer
func (_e *MockRancherClient_Expecter) ListClusters(ctx interface{}, token interface{}, server interface{}) *MockRancherClient_ListClusters_Call {
	return &MockRancherClient_ListClusters_Call{Call: _e.mock.On("ListClusters", ctx, token, server)}
}

func (_c *MockRancherClient_ListClusters_Call) Run(run func(ctx context.Context, token domain.AuthToken, server domain.ConfigServer)) *MockRancherClient_ListClusters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.AuthToken
		if args[1] != nil {
			arg1 = args[1].(domain.AuthToken)
		}
		var arg2 domain.ConfigServer
		if args[2] != nil {
			arg2 = args[2].(domain.ConfigServer)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRancherClient_ListClusters_Call) Return(clusters []domain.Cluster, err error) *MockRancherClient_ListClusters_Call {
	_c.Call.Return(clusters, err)
	return _c
}

func (_c *MockRancherClient_ListClusters_Call) RunAndReturn(run func(ctx context.Context, token domain.AuthToken, server domain.ConfigServer) ([]domain.Cluster, error)) *MockRancherClient_ListClusters_Call {
	_c.Call.Return(run)
	return _c
}
