// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"cowpoke/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRancherAuthenticator creates a new instance of MockRancherAuthenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRancherAuthenticator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRancherAuthenticator {
	mock := &MockRancherAuthenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRancherAuthenticator is an autogenerated mock type for the RancherAuthenticator type
type MockRancherAuthenticator struct {
	mock.Mock
}

type MockRancherAuthenticator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRancherAuthenticator) EXPECT() *MockRancherAuthenticator_Expecter {
	return &MockRancherAuthenticator_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type MockRancherAuthenticator
func (_mock *MockRancherAuthenticator) Authenticate(ctx context.Context, server domain.ConfigServer, password string) (domain.AuthToken, error) {
	ret := _mock.Called(ctx, server, password)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 domain.AuthToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ConfigServer, string) (domain.AuthToken, error)); ok {
		return returnFunc(ctx, server, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ConfigServer, string) domain.AuthToken); ok {
		r0 = returnFunc(ctx, server, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.AuthToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ConfigServer, string) error); ok {
		r1 = returnFunc(ctx, server, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRancherAuthenticator_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockRancherAuthenticator_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - server domain.ConfigServer
//   - password string
func (_e *MockRancherAuthenticator_Expecter) Authenticate(ctx interface{}, server interface{}, password interface{}) *MockRancherAuthenticator_Authenticate_Call {
	return &MockRancherAuthenticator_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, server, password)}
}

func (_c *MockRancherAuthenticator_Authenticate_Call) Run(run func(ctx context.Context, server domain.ConfigServer, password string)) *MockRancherAuthenticator_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ConfigServer
		if args[1] != nil {
			arg1 = args[1].(domain.ConfigServer)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRancherAuthenticator_Authenticate_Call) Return(authToken domain.AuthToken, err error) *MockRancherAuthenticator_Authenticate_Call {
	_c.Call.Return(authToken, err)
	return _c
}

func (_c *MockRancherAuthenticator_Authenticate_Call) RunAndReturn(run func(ctx context.Context, server domain.ConfigServer, password string) (domain.AuthToken, error)) *MockRancherAuthenticator_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}
