// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockKubeconfigWriter creates a new instance of MockKubeconfigWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKubeconfigWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKubeconfigWriter {
	mock := &MockKubeconfigWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKubeconfigWriter is an autogenerated mock type for the KubeconfigWriter type
type MockKubeconfigWriter struct {
	mock.Mock
}

type MockKubeconfigWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKubeconfigWriter) EXPECT() *MockKubeconfigWriter_Expecter {
	return &MockKubeconfigWriter_Expecter{mock: &_m.Mock}
}

// SaveKubeconfig provides a mock function for the type MockKubeconfigWriter
func (_mock *MockKubeconfigWriter) SaveKubeconfig(ctx context.Context, path string, content []byte, serverID string) error {
	ret := _mock.Called(ctx, path, content, serverID)

	if len(ret) == 0 {
		panic("no return value specified for SaveKubeconfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, string) error); ok {
		r0 = returnFunc(ctx, path, content, serverID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKubeconfigWriter_SaveKubeconfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveKubeconfig'
type MockKubeconfigWriter_SaveKubeconfig_Call struct {
	*mock.Call
}

// SaveKubeconfig is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - content []byte
//   - serverID string
func (_e *MockKubeconfigWriter_Expecter) SaveKubeconfig(ctx interface{}, path interface{}, content interface{}, serverID interface{}) *MockKubeconfigWriter_SaveKubeconfig_Call {
	return &MockKubeconfigWriter_SaveKubeconfig_Call{Call: _e.mock.On("SaveKubeconfig", ctx, path, content, serverID)}
}

func (_c *MockKubeconfigWriter_SaveKubeconfig_Call) Run(run func(ctx context.Context, path string, content []byte, serverID string)) *MockKubeconfigWriter_SaveKubeconfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockKubeconfigWriter_SaveKubeconfig_Call) Return(err error) *MockKubeconfigWriter_SaveKubeconfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKubeconfigWriter_SaveKubeconfig_Call) RunAndReturn(run func(ctx context.Context, path string, content []byte, serverID string) error) *MockKubeconfigWriter_SaveKubeconfig_Call {
	_c.Call.Return(run)
	return _c
}
