// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockClusterFilter creates a new instance of MockClusterFilter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClusterFilter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClusterFilter {
	mock := &MockClusterFilter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClusterFilter is an autogenerated mock type for the ClusterFilter type
type MockClusterFilter struct {
	mock.Mock
}

type MockClusterFilter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClusterFilter) EXPECT() *MockClusterFilter_Expecter {
	return &MockClusterFilter_Expecter{mock: &_m.Mock}
}

// ShouldExclude provides a mock function for the type MockClusterFilter
func (_mock *MockClusterFilter) ShouldExclude(clusterName string) bool {
	ret := _mock.Called(clusterName)

	if len(ret) == 0 {
		panic("no return value specified for ShouldExclude")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(clusterName)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockClusterFilter_ShouldExclude_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShouldExclude'
type MockClusterFilter_ShouldExclude_Call struct {
	*mock.Call
}

// ShouldExclude is a helper method to define mock.On call
//   - clusterName string
func (_e *MockClusterFilter_Expecter) ShouldExclude(clusterName interface{}) *MockClusterFilter_ShouldExclude_Call {
	return &MockClusterFilter_ShouldExclude_Call{Call: _e.mock.On("ShouldExclude", clusterName)}
}

func (_c *MockClusterFilter_ShouldExclude_Call) Run(run func(clusterName string)) *MockClusterFilter_ShouldExclude_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClusterFilter_ShouldExclude_Call) Return(b bool) *MockClusterFilter_ShouldExclude_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockClusterFilter_ShouldExclude_Call) RunAndReturn(run func(clusterName string) bool) *MockClusterFilter_ShouldExclude_Call {
	_c.Call.Return(run)
	return _c
}
