// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockKubeconfigHandler creates a new instance of MockKubeconfigHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKubeconfigHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKubeconfigHandler {
	mock := &MockKubeconfigHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKubeconfigHandler is an autogenerated mock type for the KubeconfigHandler type
type MockKubeconfigHandler struct {
	mock.Mock
}

type MockKubeconfigHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKubeconfigHandler) EXPECT() *MockKubeconfigHandler_Expecter {
	return &MockKubeconfigHandler_Expecter{mock: &_m.Mock}
}

// CleanupTempFiles provides a mock function for the type MockKubeconfigHandler
func (_mock *MockKubeconfigHandler) CleanupTempFiles(ctx context.Context, paths []string) error {
	ret := _mock.Called(ctx, paths)

	if len(ret) == 0 {
		panic("no return value specified for CleanupTempFiles")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, paths)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKubeconfigHandler_CleanupTempFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupTempFiles'
type MockKubeconfigHandler_CleanupTempFiles_Call struct {
	*mock.Call
}

// CleanupTempFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - paths []string
func (_e *MockKubeconfigHandler_Expecter) CleanupTempFiles(ctx interface{}, paths interface{}) *MockKubeconfigHandler_CleanupTempFiles_Call {
	return &MockKubeconfigHandler_CleanupTempFiles_Call{Call: _e.mock.On("CleanupTempFiles", ctx, paths)}
}

func (_c *MockKubeconfigHandler_CleanupTempFiles_Call) Run(run func(ctx context.Context, paths []string)) *MockKubeconfigHandler_CleanupTempFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKubeconfigHandler_CleanupTempFiles_Call) Return(err error) *MockKubeconfigHandler_CleanupTempFiles_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKubeconfigHandler_CleanupTempFiles_Call) RunAndReturn(run func(ctx context.Context, paths []string) error) *MockKubeconfigHandler_CleanupTempFiles_Call {
	_c.Call.Return(run)
	return _c
}

// MergeKubeconfigs provides a mock function for the type MockKubeconfigHandler
func (_mock *MockKubeconfigHandler) MergeKubeconfigs(ctx context.Context, paths []string, outputPath string) error {
	ret := _mock.Called(ctx, paths, outputPath)

	if len(ret) == 0 {
		panic("no return value specified for MergeKubeconfigs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string) error); ok {
		r0 = returnFunc(ctx, paths, outputPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKubeconfigHandler_MergeKubeconfigs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergeKubeconfigs'
type MockKubeconfigHandler_MergeKubeconfigs_Call struct {
	*mock.Call
}

// MergeKubeconfigs is a helper method to define mock.On call
//   - ctx context.Context
//   - paths []string
//   - outputPath string
func (_e *MockKubeconfigHandler_Expecter) MergeKubeconfigs(ctx interface{}, paths interface{}, outputPath interface{}) *MockKubeconfigHandler_MergeKubeconfigs_Call {
	return &MockKubeconfigHandler_MergeKubeconfigs_Call{Call: _e.mock.On("MergeKubeconfigs", ctx, paths, outputPath)}
}

func (_c *MockKubeconfigHandler_MergeKubeconfigs_Call) Run(run func(ctx context.Context, paths []string, outputPath string)) *MockKubeconfigHandler_MergeKubeconfigs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKubeconfigHandler_MergeKubeconfigs_Call) Return(err error) *MockKubeconfigHandler_MergeKubeconfigs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKubeconfigHandler_MergeKubeconfigs_Call) RunAndReturn(run func(ctx context.Context, paths []string, outputPath string) error) *MockKubeconfigHandler_MergeKubeconfigs_Call {
	_c.Call.Return(run)
	return _c
}

// SaveKubeconfig provides a mock function for the type MockKubeconfigHandler
func (_mock *MockKubeconfigHandler) SaveKubeconfig(ctx context.Context, path string, content []byte, serverID string) error {
	ret := _mock.Called(ctx, path, content, serverID)

	if len(ret) == 0 {
		panic("no return value specified for SaveKubeconfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, string) error); ok {
		r0 = returnFunc(ctx, path, content, serverID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKubeconfigHandler_SaveKubeconfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveKubeconfig'
type MockKubeconfigHandler_SaveKubeconfig_Call struct {
	*mock.Call
}

// SaveKubeconfig is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - content []byte
//   - serverID string
func (_e *MockKubeconfigHandler_Expecter) SaveKubeconfig(ctx interface{}, path interface{}, content interface{}, serverID interface{}) *MockKubeconfigHandler_SaveKubeconfig_Call {
	return &MockKubeconfigHandler_SaveKubeconfig_Call{Call: _e.mock.On("SaveKubeconfig", ctx, path, content, serverID)}
}

func (_c *MockKubeconfigHandler_SaveKubeconfig_Call) Run(run func(ctx context.Context, path string, content []byte, serverID string)) *MockKubeconfigHandler_SaveKubeconfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockKubeconfigHandler_SaveKubeconfig_Call) Return(err error) *MockKubeconfigHandler_SaveKubeconfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKubeconfigHandler_SaveKubeconfig_Call) RunAndReturn(run func(ctx context.Context, path string, content []byte, serverID string) error) *MockKubeconfigHandler_SaveKubeconfig_Call {
	_c.Call.Return(run)
	return _c
}
