version: 2

project_name: cowpoke

before:
  hooks:
  - go mod tidy
  - go test ./...

builds:
- id: cowpoke
  main: ./main.go
  binary: cowpoke

  env:
  - CGO_ENABLED=0

  goos:
  - linux
  - darwin

  goarch:
  - amd64
  - arm64
  - arm

  goarm:
  - "6"
  - "7"

  flags:
  - -trimpath

  ldflags:
  - -s -w
  - -X main.version={{.Version}}
  - -X main.commit={{.Commit}}
  - -X main.date={{.Date}}
  - -X main.builtBy=goreleaser

archives:
- id: cowpoke

  name_template: >-
    {{ .ProjectName }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{- else if eq .Arch "386" }}i386 {{- else }}{{ .Arch }}{{ end }} {{- if .Arm }}v{{ .Arm }}{{ end }}

  files:
  - README.md
  - LICENSE*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^ci:'
    - '^chore:'
    - '^style:'
    - Merge pull request
    - Merge branch
    - go mod tidy
  groups:
  - title: Features
    regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
    order: 0
  - title: 'Bug fixes'
    regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
    order: 1
  - title: 'Performance improvements'
    regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
    order: 2
  - title: Others
    order: 999

homebrew_casks:
- name: cowpoke
  repository:
    owner: imandrew
    name: homebrew-tap
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
  homepage: "https://github.com/imandrew/cowpoke"
  description: "CLI tool for syncing kubeconfigs from multiple Rancher servers"
  hooks:
    post:
      install: |
        if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
          system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cowpoke"]
        end

release:
  prerelease: auto
